name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: companyservices
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Set Cosmos DB Key as Environment Variable
        run: echo "COSMOS_DB_KEY=${{ secrets.COSMOS_DB_KEY }}" >> $GITHUB_ENV
        
      - name: Restore
        run: dotnet restore ./CompanyService.sln

      - name: Build
        run: dotnet build ./CompanyService.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./CompanyService.sln --configuration Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          
